#!/usr/bin/env bash

link_arg=$1

if [ ! "$1" ];then
    echo "You need to provide /Path/to/dir/filename."
else
    slash_num=$(echo "$link_arg" | grep -o "/" | wc -l)
    if ((slash_num < 1)); then
        echo "Not valid parameter." >&2
        exit 1
    fi
fi

src_path="${link_arg%/*}"

mkdir -p $src_path && touch $link_arg